// <auto-generated />
using System;
using GerenciarProcessos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GerenciarProcessos.Migrations
{
    [DbContext(typeof(GerenciarProcessosContext))]
    [Migration("20191106024158_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GerenciarProcessos.Models.Associacao", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteID1");

                    b.Property<int>("ProcessoID");

                    b.HasKey("ClienteID");

                    b.HasIndex("ClienteID1");

                    b.HasIndex("ProcessoID");

                    b.ToTable("Associacao");
                });

            modelBuilder.Entity("GerenciarProcessos.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cnpj");

                    b.Property<string>("Estado");

                    b.Property<string>("Nome");

                    b.HasKey("ClienteID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("GerenciarProcessos.Models.Processo", b =>
                {
                    b.Property<int>("ProcessoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteID");

                    b.Property<DateTime>("Data");

                    b.Property<bool>("Estaativo");

                    b.Property<string>("Estado");

                    b.Property<string>("Numero");

                    b.Property<int>("Valor");

                    b.HasKey("ProcessoID");

                    b.ToTable("Processo");
                });

            modelBuilder.Entity("GerenciarProcessos.Models.Associacao", b =>
                {
                    b.HasOne("GerenciarProcessos.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID1");

                    b.HasOne("GerenciarProcessos.Models.Processo", "Processo")
                        .WithMany("Associacoes")
                        .HasForeignKey("ProcessoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
